#!/usr/bin/env bash        

# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 


usage() { 
    printf "NAME\n\trun - Main driver to run RASER\n"
    printf "\nSYNOPSIS\n"
    printf "\n\t%-5s\n" "./run [OPTION]" 
    printf "\nOPTIONS\n"    
    printf "\n\t%-9s  %-40s"  "0.1"       "RASER 2D"
	printf "\n\t%-9s  %-40s"  "0.2"       "RASER 3D" 
	printf "\n\t%-9s  %-40s"  "0.3"       "RASER LGAD"
    printf "\n\n" 
}

usage_0_1() { 
    printf "\n\t%-5s  %-40s\n"  "0.1.1"    "RASER 2D SiC basic information" 
    printf "\n\t%-5s  %-40s\n"  "0.1.2"    "2D batch model" 
    printf "\n\t%-5s  %-40s\n"  "0.1.3"    "raser 2D scan for time resolution... used by 0.1.2" 
    printf "\n\t%-5s  %-40s\n"  "0.1.4"    "get time resolution 2D" 
}
usage_0_2() { 
    printf "\n\t%-5s  %-40s\n"  "0.2.1"    "RASER 3D SiC basic information" 
    printf "\n\t%-5s  %-40s\n"  "0.2.2"    "3D batch model" 
    printf "\n\t%-5s  %-40s\n"  "0.2.3"    "raser 2D scan for time resolution... used by 0.2.2" 
	printf "\n\t%-5s  %-40s\n"  "0.2.4"    "Stop Batch background operation" 
}
usage_0_3() { 
    printf "\n\t%-5s  %-40s\n"  "0.3.1"    "RASER 2D LGAD" 
	printf "\n\t%-5s  %-40s\n"  "0.3.2"    "RASER 2D PIN"
}
if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
	source singularity_bashrc.sh	
    option=$1 
	input_para=$* 
fi

sub_0_1(){
case $option in 
	
    0.1.1) echo "raser 2D SiC basic information..."
        ./python/raser.py 3D 2D 0    
        ;;
    0.1.2) echo "2D batch model"
        ./python/run_job.py 2D sub_10 total_10  instance_0 voltage_-500 output=out/2021815_2DPIN
        ;;
    0.1.3) echo "raser 2D scan for time resolution... used by 0.1.2"
        ./python/raser.py  ${input_para}
        ;;

    0.1.4) echo "get time resolution 2D"
        singularity exec raser.simg ./python/add_noise_raser.py out/2021815_2DPIN/voltage_500.0 out/2021815_2DPIN/sic_timing_result.root
        esac
}
 
sub_0_2(){
time_3D=2021_8_25_3D
case $option in 
    0.2.1) echo "raser 3D SiC basic information..."
        ./python/raser.py 3D 3D  0 		#0 is geant4 visualization useless, 1 is useful
        ;;
	0.2.2) echo "3D batch model"
        ./python/run_job.py 3D sub_10 total_10  instance_0 voltage_-500 output=out/2021826_3D
        ;;
    0.2.3) echo "raser 3D scan for time resolution... used by 0.2.2"
		./python/raser.py  ${input_para}
		;;
    0.2.4) echo "Stop Batch background operation"
        singularity instance stop --all
        esac
}
 

sub_0_3(){
Time=2021_5_28
case $option in 
    0.3.1) echo "raser 2D lgad electric field..."
		python3 python/raser.py 2D_SiC_LGAD
    	;;
    0.3.2) echo "raser 2D PIN electric field..."
		python3 python/raser.py 2D_SiC_PIN
		;;
	0.3.3) echo "raser 2D PIN TCT electric field..."
	    python3 python/raser.py 2D_LASER_SI_PIN
		;;
    0.3.4) echo "vmax compre"
        mkdir figure/ -p
        python3 python/draw_Vmax_com.py pin_compre
        ;;
    0.3.5) echo "vmax compre"
        python3 python/draw_Vmax_com.py pin_vbias
        ;;
		esac
}




case $option in 
   0.1) echo "RASER 2D"
        usage_0_1
        echo "Please enter your option: " 
        read option 
        sub_0_1 option 
        ;;
    0.1.*) echo "RASER 2D"
        sub_0_1 option
        ;;
   0.2) echo "RASER 3D"
        usage_0_2
        echo "Please enter your option: " 
        read option 
        sub_0_2 option 
        ;;
    0.2.*) echo "RASER 3D"
        sub_0_2 option 
		;;
   0.3) echo "RASER LGAD"
        usage_0_3
        echo "Please enter your option: " 
        read option 
        sub_0_3 option 
        ;;
    0.3.*) echo "RASER LGAD"
        sub_0_3 option 
		esac
