#!/usr/bin/env bash        

# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 


usage() { 
    printf "NAME\n\trun - Main driver to run RASER\n"
    printf "\nSYNOPSIS\n"
    printf "\n\t%-5s\n" "./run [OPTION]" 
    printf "\nOPTIONS\n"    
    printf "\n\t%-9s  %-40s"  "0.1"       "RASER 2D"
	printf "\n\t%-9s  %-40s"  "0.2"       "RASER 3D" 
	printf "\n\t%-9s  %-40s"  "0.3"       "RASER LGAD"
    printf "\n\n" 
}

usage_0_1() { 
    printf "\n\t%-5s  %-40s\n"  "0.1.1"    "raser planar3D SiC basic information..." 
    printf "\n\t%-5s  %-40s\n"  "0.1.2"    "planar3D batch model" 
    printf "\n\t%-5s  %-40s\n"  "0.1.3"    "raser planar3D scan for time resolution... used by 0.1.2" 
    printf "\n\t%-5s  %-40s\n"  "0.1.4"    "get time resolution planar3D" 
    printf "\n\t%-5s  %-40s\n"  "0.1.5"    "planar3D unit test" 
}
usage_0_2() { 
    printf "\n\t%-5s  %-40s\n"  "0.2.1"    "raser plugin3D SiC basic information..." 
    printf "\n\t%-5s  %-40s\n"  "0.2.2"    "plugin3D batch model" 
    printf "\n\t%-5s  %-40s\n"  "0.2.3"    "raser plugin3D scan for time resolution... used by 0.2.2" 
	printf "\n\t%-5s  %-40s\n"  "0.2.4"    "get time resolution plugin3D"
	printf "\n\t%-5s  %-40s\n"  "0.2.5"    "plugin3D unit test"  
	printf "\n\t%-5s  %-40s\n"  "0.2.6"    "singularity instance stop --all" 
}
usage_0_3() { 
    printf "\n\t%-5s  %-40s\n"  "0.3.1"    "RASER 2D LGAD" 
	printf "\n\t%-5s  %-40s\n"  "0.3.2"    "RASER 2D PIN"
}
if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
	source singularity_bashrc.sh	
    option=$1 
	input_para=$* 
fi

sub_0_1(){
case $option in 
	
    0.1.1) echo "raser planar3 SiC basic information..."
        ./pyraser/raser.py det_model=planar3D 
        ;;
    0.1.2) echo "planar3 batch model"
        ./pyraser/run_job.py det_model=planar3D step=10 total=10  \
							 instance=0 output=out/planar3Dscan/2021831_3D
        ;;
    0.1.3) echo "raser planar3 scan for time resolution... used by 0.1.2"
        ./pyraser/raser.py  ${input_para:5:100}
        ;;
    0.1.4) echo "get time resolution planar3"
        singularity exec raser.simg ./pyraser/add_noise_raser.py  out/planar3Dscan/2021815_planar3D_d:10_v:-500.0_g:150.0
        ;;
	0.1.5) echo "unit test"
        ./pyraser/unittext/test.py det_model=planar3Dscan
        esac
}
 
sub_0_2(){
case $option in 
    0.2.1) echo "raser plugin3D SiC basic information..."
        ./pyraser/raser.py det_model=plugin3D 		
        ;;
	0.2.2) echo "plugin3D batch model"
        ./pyraser/run_job.py det_model=plugin3D step=10 total=10  \
							 instance=0 output=out/plugin3Dscan/2021831_3D
        ;;
    0.2.3) echo "raser plugin3D scan for time resolution... used by 0.2.2"
		./pyraser/raser.py  ${input_para:5:100}
		;;
    0.2.4) echo "get time resolution plugin3D"
        singularity exec raser.simg ./pyraser/add_noise_raser.py  out/plugin3Dscan/2021815_planar3D_d:10_v:-500.0_g:150.0
        ;;
	0.2.5) echo "unit test"
        ./pyraser/unittext/test.py det_model=plugin3Dscan
		;;
    0.2.6) echo "Stop Batch background operation"
        singularity instance stop --all
		;;
        esac
}
 

sub_0_3(){
Time=2021_5_28
case $option in 
    0.3.1) echo "raser 2D lgad electric field..."
		python3 python/raser.py 2D_SiC_LGAD
    	;;
    0.3.2) echo "raser 2D PIN electric field..."
		python3 python/raser.py 2D_SiC_PIN
		;;
	0.3.3) echo "raser 2D PIN TCT electric field..."
	    python3 python/raser.py 2D_LASER_SI_PIN
		;;
    0.3.4) echo "vmax compre"
        python3 python/draw.py pin_compre
        ;;
    0.3.5) echo "vmax compre"
        python3 python/draw.py pin_vbias
        ;;
		esac
}




case $option in 
   0.1) echo "RASER 2D"
        usage_0_1
        echo "Please enter your option: " 
        read option 
        sub_0_1 option 
        ;;
    0.1.*) echo "RASER 2D"
        sub_0_1 option
        ;;
   0.2) echo "RASER 3D"
        usage_0_2
        echo "Please enter your option: " 
        read option 
        sub_0_2 option 
        ;;
    0.2.*) echo "RASER 3D"
        sub_0_2 option 
		;;
   0.3) echo "RASER LGAD"
        usage_0_3
        echo "Please enter your option: " 
        read option 
        sub_0_3 option 
        ;;
    0.3.*) echo "RASER LGAD"
        sub_0_3 option 
		esac
