#!/usr/bin/env bash        

# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 


usage() { 
    printf "NAME\n\trun - Main driver to run RASER\n"
    printf "\nSYNOPSIS\n"
    printf "\n\t%-5s\n" "./run [OPTION]" 
    printf "\nOPTIONS\n"    
    printf "\n\t%-9s  %-40s"  "0.1"       "RASER 2D"
	printf "\n\t%-9s  %-40s"  "0.2"       "RASER 3D" 
	printf "\n\t%-9s  %-40s"  "0.3"       "RASER LGAD"
    printf "\n\n" 
}

usage_0_1() { 
    printf "\n\t%-5s  %-40s\n"  "0.1.1"    "RASER 2D SiC basic information" 
    printf "\n\t%-5s  %-40s\n"  "0.1.2"    "RASER 2D scan for time resolution" 
    printf "\n\t%-5s  %-40s\n"  "0.1.3"    "data processing 2D" 
    printf "\n\t%-5s  %-40s\n"  "0.1.4"    "get time resolution 2D" 
}
usage_0_2() { 
    printf "\n\t%-5s  %-40s\n"  "0.2.1"    "RASER 3D SiC basic information" 
    printf "\n\t%-5s  %-40s\n"  "0.2.2"    "RASER 3D scan for time resolution" 
    printf "\n\t%-5s  %-40s\n"  "0.2.3"    "data processing 3D" 
    printf "\n\t%-5s  %-40s\n"  "0.2.4"    "get time resolution 3D" 
    printf "\n\t%-5s  %-40s\n"  "0.2.5"    "Batch background operation" 
}
usage_0_3() { 
    printf "\n\t%-5s  %-40s\n"  "0.3.1"    "RASER 2D LGAD Electrical Field" 
}
if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
    option=$1 
    number=$2  
    t_number=$3
    step_n=$4 
    change_p=$5   
fi

sub_0_1(){
time_2D=2021_7_13
case $option in 
    0.1.1) echo "raser 2D SiC basic information..."
        python3 python/raser_3D.py 2D  
        ;;
    0.1.2) echo "batch model"
        python3 python/run_job.py 2000 10000 35.0 0
        python3 python/run_job.py 2000 10000 35.0 5
        python3 python/run_job.py 2000 10000 35.0 10
        python3 python/run_job.py 2000 10000 35.0 15
        python3 python/run_job.py 2000 10000 35.0 20
        ;;
    0.1.3) echo "raser 2D scan for time resolution..."
        mkdir out/fenics_${time_2D}/ -p
        rm out/fenics_${time_2D}/* -rf
        python3 python/raser_3D.py 2D_scan out/fenics_${time_2D}/ ${number} ${t_number} ${step_n} ${change_p}
        ;;
    0.1.4) echo "data processing"
        mkdir result/sic_${time_2D}_result/ -p
        rm result/sic_${time_2D}_result/*
        python3 python/raser_read_sample.py out/fenics_${time_2D}/twoD_voltage_500/ result/sic_${time_2D}_result/ V
        ;;
    0.1.5) echo "get time resolution"
        mkdir result/root -p
        python3 python/add_noise_raser.py result/sic_${time_2D}_result/ result/root/sic_${time_2D}_result.root
        esac
}
 
sub_0_2(){
time_gap=2021_6_18_3D_gap_scan
time_voltage=2021_6_18_3D_voltage_scan

case $option in 
    0.2.1) echo "raser 3D SiC basic information..."
        mkdir fig/ -p
        python3 python/raser_3D.py 3D  
        ;;
    0.2.2) echo "raser 3D scan for time resolution..."
        mkdir out/fenics_${time_gap}/ -p
        #python3 python/raser_3D.py 3D_scan out/fenics_${time_gap} ${number} ${t_number} ${step_n} ${change_p}
		python3 python/run_job_3D.py 3D_scan out/fenics_${time_gap} ${number} ${t_number} ${step_n} ${change_p}	
        ;;
    0.2.3) echo "data processing voltage"
        mkdir result/sic_${time_voltage}_result/gap_40_voltage_650.0 -p
        mkdir result/sic_${time_voltage}_result/gap_40_voltage_550.0 -p
        mkdir result/sic_${time_voltage}_result/gap_40_voltage_500.0 -p
        mkdir result/sic_${time_voltage}_result/gap_40_voltage_450.0 -p
        mkdir result/sic_${time_voltage}_result/gap_40_voltage_350.0 -p
        mkdir result/sic_${time_voltage}_result/gap_40_voltage_250.0 -p
        mkdir result/sic_${time_voltage}_result/gap_40_voltage_150.0 -p
        mkdir result/sic_${time_voltage}_result/gap_40_voltage_50.0 -p
        mkdir result/sic_${time_voltage}_result/gap_40_voltage_20.0 -p		
        # rm result/sic_${time_gap}_result/*
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_voltage}/gap_40_voltage_-650.0 result/sic_${time_voltage}_result/gap_40_voltage_650.0/ V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_voltage}/gap_40_voltage_-550.0 result/sic_${time_voltage}_result/gap_40_voltage_550.0/ V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_voltage}/gap_40_voltage_-500.0 result/sic_${time_voltage}_result/gap_40_voltage_500.0/ V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_voltage}/gap_40_voltage_-450.0 result/sic_${time_voltage}_result/gap_40_voltage_450.0/ V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_voltage}/gap_40_voltage_-350.0 result/sic_${time_voltage}_result/gap_40_voltage_350.0/ V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_voltage}/gap_40_voltage_-250.0 result/sic_${time_voltage}_result/gap_40_voltage_250.0/ V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_voltage}/gap_40_voltage_-150.0 result/sic_${time_voltage}_result/gap_40_voltage_150.0/ V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_voltage}/gap_40_voltage_-50.0 result/sic_${time_voltage}_result/gap_40_voltage_50.0/ V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_voltage}/gap_40_voltage_-20.0 result/sic_${time_voltage}_result/gap_40_voltage_20.0/ V

        ;;
    0.2.4) echo "data processing gap"
        rm -rf result/sic_${time_gap}_result/*
        mkdir result/sic_${time_gap}_result/gap_35_voltage_350 -p
        mkdir result/sic_${time_gap}_result/gap_30_voltage_350 -p
        mkdir result/sic_${time_gap}_result/gap_25_voltage_350 -p
        mkdir result/sic_${time_gap}_result/gap_20_voltage_350 -p
        mkdir result/sic_${time_gap}_result/gap_15_voltage_350 -p

    
        # rm result/sic_${time_gap}_result/*
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_gap}/gap_35.0_voltage_350  result/sic_${time_gap}_result/gap_35_voltage_350/  V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_gap}/gap_30.0_voltage_350  result/sic_${time_gap}_result/gap_30_voltage_350/  V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_gap}/gap_25.0_voltage_350  result/sic_${time_gap}_result/gap_25_voltage_350/  V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_gap}/gap_20.0_voltage_350  result/sic_${time_gap}_result/gap_20_voltage_350/  V
        singularity exec raser.simg python3 python/raser_read_sample.py out/fenics_${time_gap}/gap_15.0_voltage_350  result/sic_${time_gap}_result/gap_15_voltage_350/  V

        ;;
    0.2.5) echo "get time resolution voltage scan"
        mkdir result/voltage/root -p
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_voltage}_result/gap_40_voltage_650.0/ result/voltage/root/sic_${time_voltage}_650_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_voltage}_result/gap_40_voltage_550.0/ result/voltage/root/sic_${time_voltage}_550_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_voltage}_result/gap_40_voltage_500.0/ result/voltage/root/sic_${time_voltage}_500_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_voltage}_result/gap_40_voltage_450.0/ result/voltage/root/sic_${time_voltage}_450_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_voltage}_result/gap_40_voltage_350.0/ result/voltage/root/sic_${time_voltage}_350_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_voltage}_result/gap_40_voltage_250.0/ result/voltage/root/sic_${time_voltage}_250_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_voltage}_result/gap_40_voltage_150.0/ result/voltage/root/sic_${time_voltage}_150_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_voltage}_result/gap_40_voltage_50.0/ result/voltage/root/sic_${time_voltage}_50_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_voltage}_result/gap_40_voltage_20.0/ result/voltage/root/sic_${time_voltage}_20_result.root
        ;;
    0.2.6) echo "get time resolution gap"
        rm -rf result/gap/root
        mkdir result/gap/root -p
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_gap}_result/gap_44.0 result/gap/root/sic_${time_gap}_gap_44.0_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_gap}_result/gap_35_voltage_350 result/gap/root/sic_${time_gap}_gap_35_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_gap}_result/gap_30_voltage_350 result/gap/root/sic_${time_gap}_gap_30_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_gap}_result/gap_25_voltage_350 result/gap/root/sic_${time_gap}_gap_25_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_gap}_result/gap_20_voltage_350 result/gap/root/sic_${time_gap}_gap_20_result.root
        singularity exec raser.simg python3 python/add_noise_raser.py result/sic_${time_gap}_result/gap_15_voltage_350 result/gap/root/sic_${time_gap}_gap_15_result.root
        ;;
    0.2.7) echo "Batch background operation voltage scan"
        mkdir out/fenics_${time_voltage}/ -p
        python3 python/sub_job_3D.py 2000 10000 -650 5 
        python3 python/sub_job_3D.py 2000 10000 -550 10   
        python3 python/sub_job_3D.py 2000 10000 -500 15
        python3 python/sub_job_3D.py 2000 10000 -450 20
        python3 python/sub_job_3D.py 2000 10000 -350 25
        python3 python/sub_job_3D.py 2000 10000 -250 30
        python3 python/sub_job_3D.py 2000 10000 -150 35
        python3 python/sub_job_3D.py 2000 10000 -50  40
        python3 python/sub_job_3D.py 2000 10000 -20  45
        ;;
    0.2.8) echo "Batch background operation gap scan"
        mkdir out/fenics_${time_gap}/ -p
        python3 python/run_job.py 2000 10000 35.0 0
        python3 python/run_job.py 2000 10000 30.0 5
        python3 python/run_job.py 2000 10000 25.0 10
        python3 python/run_job.py 2000 10000 20.0 15
        python3 python/run_job.py 2000 10000 15.0 20
        ;;
    0.2.6) echo "Stop Batch background operation"
        singularity instance stop --all
        esac
}

sub_0_3(){
Time=2021_5_28
case $option in 
    0.3.1) echo "raser 2D lgad electric field..."
		python3 python/raser_lgad.py
    	;;
		esac
}




case $option in 
   0.1) echo "RASER 2D"
        usage_0_1
        echo "Please enter your option: " 
        read option 
        sub_0_1 option 
        ;;
    0.1.*) echo "RASER 2D"
        sub_0_1 option
        ;;
   0.2) echo "RASER 3D"
        usage_0_2
        echo "Please enter your option: " 
        read option 
        sub_0_2 option 
        ;;
    0.2.*) echo "RASER 3D"
        sub_0_2 option 
		;;
   0.3) echo "RASER LGAD"
        usage_0_3
        echo "Please enter your option: " 
        read option 
        sub_0_3 option 
        ;;
    0.3.*) echo "RASER 3D"
        sub_0_3 option 
		esac
